### ISSUE TITLE
Crashes on Entry to Chao Garden

### ISSUE THREAD

**Issue by greysondn** [SPEEPSHighway/MemeMaker#1]
I have isolated this bug to this specific mod being enabled.

Reproduction:
- Enable indicated mods in log
- Start a new save file (or any save file). If new, beat Chaos 0.
- Enter the Chao Garden
- CRASH.

The attached zip file includes the debug log from the modloader, the save I used to generate that debug log, and the chaos garden save generated when doing that process. The adventure save was just after Chaos 0 was defeated, with no chao garden save generated yet.

[SPEEPSHighway_MemeMaker_Issue_1.zip](https://github.com/SPEEPSHighway/MemeMaker/files/7491424/SPEEPSHighway_MemeMaker_Issue_1.zip)

**Comment by SPEEPSHighway** [comment]
Thanks, should be fixed now.
